In [3]:
import numpy as np


# Gerar array com 100 posições de 0 até 100 (exclusivo)

In [11]:
A = np.arange(100)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Alterando cada elemento de uma matriz iterativamente:

In [4]:
A = np.identity(10, 'int')
for i,x in np.ndenumerate(A):
  a = np.random.randint(1,10)
  A[i] = a
A

array([[8, 9, 4, 8, 2, 4, 4, 1, 5, 7],
       [8, 6, 1, 1, 8, 3, 2, 4, 6, 2],
       [5, 4, 1, 5, 6, 4, 6, 2, 5, 2],
       [9, 9, 5, 7, 2, 3, 5, 8, 3, 1],
       [1, 9, 3, 1, 6, 9, 5, 2, 7, 9],
       [8, 8, 3, 1, 9, 6, 2, 8, 4, 5],
       [6, 4, 9, 3, 4, 1, 8, 7, 7, 2],
       [7, 8, 2, 6, 4, 5, 6, 6, 9, 9],
       [5, 1, 6, 2, 9, 5, 2, 8, 3, 2],
       [5, 4, 3, 4, 1, 6, 6, 7, 7, 4]])

array([ 6,  7,  8,  9, 10])